---
- name: Create demo user
  hosts: "{{ remote_hosts }}"
  remote_user: "{{ remote_login }}"
  become: true
  become_method: sudo

  # python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw)
  # if (pw==getpass.getpass("Confirm: ")) else exit())'
  vars:
    users:
      - user: wafa
        password: $6$y/mVLiIApUiMqNtA$RypiljN.uEYeDa5MmxyF3f64T3auL5La7AQUdZHY.QiRfITjpLf7kUVzBHDwTsMsbmw97H2tMrixtD9WhU1x6/
      - user: tahar
        password: $6$k8orxJp3wn0eA9ON$IU/SVFevEkQKQQp6c4FC562a6BXcgc7Jp.ZqiNroj58eLsVwbqb6RwvGuNvoMZZtH1N4zPsA57eht62NZrsp//
      - user: nefaa
        password: $6$brR0KPTHuTaSEUlw$XoF7/3Fhi/oTtbRIktxLxZrz1iTAiaH7wYbJ16r.iWEBSV8KanL7rFmz9ukKBC5lxQ0oxNRdNtGyZscfbeDwu1
      # - user: moulayali
      #   password: $6$mCi7xspdLhFhvV75$/B5Tcmve.TL0CGrdIOKFtt3pAH9pc.F2FBpPo4GcDFlT3JEAuK3FmI2HXwax93jHbWHDoKupF7rpHP7qxtgg/0
      - user: mohamed
        password: $6$bcjDr.5ZT6/d9eOn$TrPG0EbZeq4n4d8SNGSruh2mbgSh0o6oH9ts.0Az0kJSjGlyb5hTN.Qkiiq4zv/GD7JclIdjle6ctG.lfUfpc1
  tasks:
    - name: Create user demo
      user:
        name: "{{ item.user }}"
        shell: /bin/zsh
        createhome: true
        # group: wheel
        generate_ssh_key: true
        ssh_key_bits: 2048
        password: "{{ item.password }}"
        update_password: always
      with_items: "{{ users }}"

    - name: Add users to sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: "^root   ALL="
        line: "{{ item.user }} ALL=(ALL:ALL) ALL"
        validate: /usr/sbin/visudo -cf %s
      with_items: "{{ users }}"
