---
- name: Create demo user
  hosts: "{{ remote_hosts }}"
  remote_user: root
  become: true
  become_method: sudo

  # python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw)
  # if (pw==getpass.getpass("Confirm: ")) else exit())'
  vars:
    users:
      - user: wafa
        password: $6$y/mVLiIApUiMqNtA$RypiljN.uEYeDa5MmxyF3f64T3auL5La7AQUdZHY.QiRfITjpLf7kUVzBHDwTsMsbmw97H2tMrixtD9WhU1x6/
      - user: tahar
        password: $6$OxQg6icHAQ6zgw/5$V7znUoc6LdbO5KLclFoOaNT3U6SwAuK3eNhqVXb1RNidG8oYA5dWylUPYaN8sKaZeh0rfSyKg/.gauwWE3n/X.
      - user: nefaa
        password: $6$dbmNpul0NTYAi7Jy$Vd3Z0nMy/JvucUM6ywmzd4VUptNReZoh99c8Z3grys/tPLh0wLSl1TpLAwM4A/RQOJDQrmbPtuBRImmuaotzW/
      # - user: moulayali
      #  password: $6$s2CCgxgBJIm6PljQ$m9SfBw4QCkRYWqIbYe3VAdjGe8GJUBhTM5pbF5IapytAk0pw06fRlUbuJf8a1EjHAFhNSCxko7uNAyXAeH/.d/
  tasks:
    - name: Create user demo
      user:
        name: "{{ item.user }}"
        shell: /bin/bash
        createhome: true
        # group: wheel
        generate_ssh_key: true
        ssh_key_bits: 2048
        password: "{{ item.password }}"
        update_password: always
      with_items: "{{ users }}"

    - name: Add users to sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        insertafter: "^root   ALL="
        line: "{{ item.user }} ALL=(ALL:ALL) ALL"
        validate: /usr/sbin/visudo -cf %s
      with_items: "{{ users }}"
