---
- name: Add Windows User
  hosts: "{{ remote_hosts }}"

  vars:
    admins:
      - user: tahar
        password: "XWbH;ny9M.U$7"
        fullname: "Tahar Ben Achour"
      - user: wafa
        fullname: "Wafa Masmoudi"
        password: "4gsh+YL*K@3J4"
      - user: nefaa
        fullname: "Nefaa Haj Hassine"
        password: "7f?eiX@MH9Vheh3"
      - user: ahmed
        password: "v+exeKHM?mjif3"
        fullname: "Ahmed Nasri"
    helpdesk:
      - user: walid
        password: "dqmlhfqsdoh"
        fullname: "Walid Rouissi"
      - user: walidg
        password: "qsmlfjqmlqjsd"
        fullname: "Walid Ghanmi"
  tasks:
    - name: Ensure user {{user}} is present
      ansible.windows.win_user:
        name: "{{item.user}}"
        fullname: "{{ item.fullname }}"
        password_never_expires: true
        password: "{{item.password}}"
        state: present
        groups:
          - Administrators
          - Users
      with_items: "{{admins}}"
    


