---
- name: Add Windows User
  hosts: "{{ remote_hosts }}"

  vars:
    users:
      - user: tahar
        password: "XWbH;ny9M.U$7"
        fullname: "Tahar Ben Achour"
      - user: wafa
        fullname: "Wafa Masmoudi"
        password: "4gsh+YL*K@3J4"
      - user: keystone
        fullname: "Kystone Audit"
        password: "67ijd-kn546@4Lr?ytTRE"

  tasks:
    - name: Ensure user {{user}} is present
      ansible.windows.win_user:
        name: "{{item.user}}"
        fullname: "{{ item.fullname }}"
        password_never_expires: true
        password: "{{item.password}}"
        state: present
        groups:
          - Administrators
          - Users
      with_items: "{{users}}"
