---
- name: Add Windows User
  hosts: "{{ remote_hosts }}"

  vars:
    users:
      - user: tahar
        password: "XWbH;ny9M.U$7"
        fullname: "Tahar Ben Achour"
      - user: wafa
        fullname: "Wafa Masmoudi"
        password: "4gsh+YL*K@3J4"
      # - user: lassaad
      #   fullname: "Lassaad Belhadj"
      #   password: "kqP$kb.+cj-9r/"

  tasks:
    - name: Ensure user {{user}} is present
      ansible.windows.win_user:
        name: "{{item.user}}"
        fullname: "{{ item.fullname }}"
        password_never_expires: true
        password: "{{item.password}}"
        state: present
        groups:
          - Administrateurs
          - Utilisateurs
      with_items: "{{users}}"
