---
- name: win_copy module demo
  hosts: "{{ remote_host }}"
  become: false
  gather_facts: true
  tasks:
    - name: copy report.txt
      ansible.windows.win_copy:
        src: "{{ source }}"
        dest: "{{ destination }}"
