---
- name: testing encrypting passwords in inventory
  hosts: display01  


  tasks:
  - name: Show message
    ansible.builtin.debug:
      msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
