---
- name: Update GNU/Linux 
  hosts: "{{ remote_host }}"
  remote_user: "{{ remote_login }}"
  become: true

  tasks:
    - name: Update RedHat family
      command: dnf update -y
      when: 
        - ansible_facts['os_family'] == "RedHat"

    - name: Update Debian family
      command: apt update && apt dist-upgrade -y
      when:
        - ansible_facts['os_family'] == "Debian"
