---
- name: Remove user deploy Privileges from sudoers after installation
  hosts: "{{ remote_host }}"
  remote_user: "{{ remote_login }}"
  become: true

  tasks:
    - name: Make sure group wheel is not in the sudoers configuration
      lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: '^deploy'
