---
- hosts: "{{ remote_host }}"
  remote_user: "{{ remote_login }}"
  # become: yes
  # become_method: "sudo"
  tasks:
    - name: Change user password
      user:
        name: "{{ user_name }}"
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"
