# Run this playbook wiht the commande :
# ansible-playbook -i inventory updatePassowrd.yml --extra-vars "newpassword=yourpassword user_name=user's_changing_password"

---
- hosts: "{{ host_name }}"
  remote_user: "{{ remote_user }}"
  #become: yes
  #become_method: "sudo"
  tasks:
    - name: Change user password
      user:
        name: "{{ user_name }}"
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"